CREATE TABLE `fine_tuning_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`openaiJobId` varchar(64),
	`openaiFileId` varchar(64),
	`baseModel` varchar(64) NOT NULL DEFAULT 'gpt-4.1-mini-2025-04-14',
	`fineTunedModel` varchar(128),
	`trainingExportId` int,
	`trainingPairs` int NOT NULL DEFAULT 0,
	`epochs` int NOT NULL DEFAULT 3,
	`status` varchar(24) NOT NULL DEFAULT 'pending',
	`abTestActive` tinyint NOT NULL DEFAULT 0,
	`abTrafficPercent` int NOT NULL DEFAULT 20,
	`abStartedAt` timestamp,
	`abWins` int NOT NULL DEFAULT 0,
	`abLosses` int NOT NULL DEFAULT 0,
	`baseWins` int NOT NULL DEFAULT 0,
	`baseLosses` int NOT NULL DEFAULT 0,
	`promoted` tinyint NOT NULL DEFAULT 0,
	`promotedAt` timestamp,
	`error` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `fine_tuning_jobs_id` PRIMARY KEY(`id`)
);
