CREATE TABLE `quotes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`product` varchar(128) NOT NULL,
	`productName` varchar(255) NOT NULL,
	`qty` int NOT NULL,
	`sides` int NOT NULL,
	`perUnit` int,
	`perUnitRangeLow` int,
	`perUnitRangeHigh` int,
	`subtotal` int,
	`rushFee` int,
	`setupFee` int DEFAULT 0,
	`total` int,
	`rush` tinyint DEFAULT 0,
	`status` enum('sent','approved','declined','expired','call_for_quote') NOT NULL DEFAULT 'sent',
	`breakdown` text,
	`callForQuote` tinyint DEFAULT 0,
	`sentAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	`approvedAt` timestamp,
	`declinedAt` timestamp,
	`decisionLogId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `quotes_id` PRIMARY KEY(`id`)
);
